### ISSUE TITLE
Release 1.2 Checklist

### ISSUE THREAD

**Issue by madisonb** [istresearch/scrapy-cluster#100]
Issue to outline last bits of work to be done before 1.2 release

- [x] Create `release-1.2` branch
- [x] Clean up extra fluff in .travis.yml
- [x] Remove special `pip install scutils` from travis
- [x] Push `scutils 1.2` into PyPi
- [x] Update ELK Docker versions
- [x] Update Wurstmeister Kafka Docker Version
- [x] Update docker-compose samples for 1.2 containers
- [x] Check if we can use official [Zookeeper](https://hub.docker.com/_/zookeeper/) container vs Wurstmeister Zookeeper
- [x] Ensure Scrapy is up to date
- [x] Update pip packages
- [x] Ensure Rest Service Stats are included in Stats API, update docs
- [x] Add FAQ Question about Scrapy `start_urls`
- [x] Update `elastic=True` setting for `RedisThrottledQueue` in scheduler
- [x] Read through [docs](http://scrapy-cluster.readthedocs.io/en/dev/) fixing typos and what not
- [x] Remove docs warning header about being out of date
- [x] Create `xxx-1.2rc1` containers
- [x] Update dockerhub docs with naming conventions

**Comment by davidthewatson** [comment]
Is there a reason that #46 is not on this list?

I was going to move a bunch of scrapy code to scrapy cluster using the docker-compose containers but python 3 is a hard-stop requirement for us.

Thanks!

**Comment by madisonb** [comment]
@davidthewatson I ran into trouble supporting python 3 within the `scutils` library when using [redis-py](https://redis-py.readthedocs.io/en/latest/). That library expects keys to be strings in both python2 and python3, and I was going crazy trying to figure out how to:
a) Preserve the default `pickle` encoding and `ujson` this project uses has backwards compatibility for the library (see [here](https://github.com/istresearch/scrapy-cluster/blob/dev/utils/scutils/redis_queue.py#L15))
b) Ensure that unpacking a dictionary in python3 and python2 worked the same way, or could be supported somehow even if there needed to be different logic (see [here](https://github.com/istresearch/scrapy-cluster/blob/dev/utils/scutils/redis_queue.py#L124-L126))

I outlined my frustration [here](https://github.com/istresearch/scrapy-cluster/issues/46#issuecomment-239483616) in hopes that someone who was more familiar with python3 could help with it, and I didn't have the bandwidth at the time to figure it out. Given the new feature list for v1.2, number of bugs/issues fixed, and how long it has been since a release, I have been inclined to move forward and release support for only python2 and then focus on python 3 for the latest `dev` branch code.

However, if you are interested in supporting the project and want to try to figure it out I would love a PR and I would be happy to consider it. There are a number of things we need to support, like Ubuntu/Centos running python3, running on Travis, and Docker/Alpine based containers - so given how large that task was it was going to delay 1.2 to a degree and I figured my time is better spent cutting 1.2 and then focusing on it.

There is probably some extra python 3 compatibility refactoring to be done on the main codebase (which was done once already back in August), but I think all of that is solvable once the above mentioned issue is resolved.
