### ISSUE TITLE
UI Integration Checklist

### ISSUE THREAD

**Issue by madisonb** [istresearch/scrapy-cluster#116]
Checklist for items that I know need worked on before the [ui](https://github.com/istresearch/scrapy-cluster/tree/ui) branch can be merged into the [dev](https://github.com/istresearch/scrapy-cluster/tree/dev) branch

- [ ] Create documentation
- [ ] Add offline unit tests
- [ ] Add online integration tests
- [ ] Can we add actual ui tests? (aka Selenium or some other framework)
- [ ] Can we use the local flask app to pass requests to the Rest Endpoint, instead of the browser? (only exposing the UI port on the cluster)
- [ ] Build out primitive functionality to submit a crawl request, or get basic information about the cluster
- [ ] Ensure travis can run the unit tests

[This](https://github.com/istresearch/scrapy-cluster/issues/25#issuecomment-262146556) comment here outlines FULL functionality, however I don't think we need that to provide a basic UI for the cluster to be merged into dev.

This checklist will be updated as we come across other smaller items that prevent the `ui` branch from merging into `dev`

**Comment by damienkilgannon** [comment]
This PR #129 satisfies the following items from the above checklist:

- [x ] Create documentation
- [x ] Add offline unit tests
- [x ] Add online integration tests
- [x ] Add tests to `run_*_tests.sh`
- [ ] Can we add actual ui tests? (aka Selenium or some other framework)
- [x] Can we use the local flask app to pass requests to the Rest Endpoint, instead of the browser? (only exposing the UI port on the cluster)
- [x] Build out primitive functionality to submit a crawl request, or get basic information about the cluster
- [ ] Ensure travis can run the unit tests

**Comment by sornalingam** [comment]
Hi @madisonb , @damienkilgannon , 

I have written UI test using selenium and python  for all pages available in Scrapy Cluster. (index, Kafka, Redis and Crawler) 

But i am not sure how and where to commit my code for your review. 
Would it be possible for you to help me to share my code ?

Thanks,

**Comment by sornalingam** [comment]
Hi @damienkilgannon, 
Thanks, I have commited my new code. Please have a look when you get a chance and let me know.
