### ISSUE TITLE
Dockerization

### ISSUE THREAD

**Issue by madisonb** [istresearch/scrapy-cluster#48]
We should use Docker Swarm and Docker Compose in order to be able to spin up and spin down Scrapy Cluster and **all** it's dependencies. 

Impacts #14 #18 #26

**Comment by madisonb** [comment]
The initial cut of dockerizing all 3 components is complete. Each is scalable with docker-compose as well as within each container. 

Todo:
- [ ] Define environment variable overrides for commonly altered configurations within the `settings.py` files
- [ ] Documentation under the Advanced Topics as well as Quickstart to supply yet another alternative to working and provisioning Scrapy Cluster.
- [ ] Update Changelog
- [ ] Merge branch back into `dev`
- [ ] Dockerhub builds, or at least a stable set of images on the hub for people to pull down

Note that Dockerhub is not compatible with both build context and dockerfile params (which we need here), so I may have to resort to manual pushing for now
